export const IB_CURVE_GET_CURRENCY_DATA_BEGIN = 'IB_CURVE_GET_CURRENCY_DATA_BEGIN';
export const IB_CURVE_GET_CURRENCY_DATA_SUCCESS = 'IB_CURVE_GET_CURRENCY_DATA_SUCCESS';
export const IB_CURVE_GET_CURRENCY_DATA_FAILURE = 'IB_CURVE_GET_CURRENCY_DATA_FAILURE';
export const IB_CURVE_GET_CURRENCY_DATA_DISMISS_ERROR = 'IB_CURVE_GET_CURRENCY_DATA_DISMISS_ERROR';
export const IB_CURVE_UPDATE_DATA = 'IB_CURVE_UPDATE_DATA';
export const IB_CURVE_UPDATE_CURRENCY_LIST = 'IB_CURVE_UPDATE_CURRENCY_LIST';
export const IB_CURVE_UPDATE_REAL_TIME_DATA = 'IB_CURVE_UPDATE_REAL_TIME_DATA';